<?php

/**
 * BaseUserInfo
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property decimal $balance
 * @property datetime $last_payday
 * 
 * @method integer  getUserId()      Returns the current record's "user_id" value
 * @method decimal  getBalance()     Returns the current record's "balance" value
 * @method datetime getLastPayday()  Returns the current record's "last_payday" value
 * @method UserInfo setUserId()      Sets the current record's "user_id" value
 * @method UserInfo setBalance()     Sets the current record's "balance" value
 * @method UserInfo setLastPayday()  Sets the current record's "last_payday" value
 * 
 * @package    OddsThomas
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUserInfo extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('user_info');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('balance', 'decimal', null, array(
             'type' => 'decimal',
             ));
        $this->hasColumn('last_payday', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}