<?php

/**
 * BaseBet
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $bet_id
 * @property integer $user_id
 * @property integer $game_id
 * @property string $pick
 * @property string $odds
 * @property string $amount
 * @property Game $Game
 * 
 * @method integer getBetId()   Returns the current record's "bet_id" value
 * @method integer getUserId()  Returns the current record's "user_id" value
 * @method integer getGameId()  Returns the current record's "game_id" value
 * @method string  getPick()    Returns the current record's "pick" value
 * @method string  getOdds()    Returns the current record's "odds" value
 * @method string  getAmount()  Returns the current record's "amount" value
 * @method Game    getGame()    Returns the current record's "Game" value
 * @method Bet     setBetId()   Sets the current record's "bet_id" value
 * @method Bet     setUserId()  Sets the current record's "user_id" value
 * @method Bet     setGameId()  Sets the current record's "game_id" value
 * @method Bet     setPick()    Sets the current record's "pick" value
 * @method Bet     setOdds()    Sets the current record's "odds" value
 * @method Bet     setAmount()  Sets the current record's "amount" value
 * @method Bet     setGame()    Sets the current record's "Game" value
 * 
 * @package    OddsThomas
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseBet extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('bet');
        $this->hasColumn('bet_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('pick', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('odds', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('amount', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Game', array(
             'local' => 'game_id',
             'foreign' => 'game_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}