<?php

/**
 * BaseGame
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $game_id
 * @property string $team1
 * @property string $team2
 * @property string $result
 * @property boolean $active
 * @property Doctrine_Collection $Odds
 * @property Doctrine_Collection $Bet
 * 
 * @method integer             getGameId()  Returns the current record's "game_id" value
 * @method string              getTeam1()   Returns the current record's "team1" value
 * @method string              getTeam2()   Returns the current record's "team2" value
 * @method string              getResult()  Returns the current record's "result" value
 * @method boolean             getActive()  Returns the current record's "active" value
 * @method Doctrine_Collection getOdds()    Returns the current record's "Odds" collection
 * @method Doctrine_Collection getBet()     Returns the current record's "Bet" collection
 * @method Game                setGameId()  Sets the current record's "game_id" value
 * @method Game                setTeam1()   Sets the current record's "team1" value
 * @method Game                setTeam2()   Sets the current record's "team2" value
 * @method Game                setResult()  Sets the current record's "result" value
 * @method Game                setActive()  Sets the current record's "active" value
 * @method Game                setOdds()    Sets the current record's "Odds" collection
 * @method Game                setBet()     Sets the current record's "Bet" collection
 * 
 * @package    OddsThomas
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGame extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('game');
        $this->hasColumn('game_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('team1', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('team2', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('result', 'string', 10, array(
             'type' => 'string',
             'length' => 10,
             ));
        $this->hasColumn('active', 'boolean', null, array(
             'type' => 'boolean',
             'default' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Odds', array(
             'local' => 'game_id',
             'foreign' => 'game_id'));

        $this->hasMany('Bet', array(
             'local' => 'game_id',
             'foreign' => 'game_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}