<?php

/**
 * Game
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OddsThomas
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Game extends BaseGame
{

	public function  __toString()
	{
		$name = $this->getTeam1() . " vs. " . $this->getTeam2();
		return $name;
	}
}
