<?php

/**
 * Odds
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    OddsThomas
 * @subpackage model
 * @author     druid628
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Odds extends BaseOdds
{
	public function save(Doctrine_Connection $con = null)
	{
		$this->deactivateOthers();
		parent::save();
	}

	public function deactivateOthers()
	{
		$q = Doctrine_Query::create()
			->update('Odds o')
			->set('active', '0')
		    	->where('o.game_id = ' . $this->getGameId())
		       	->andWhere('o.active = 1')
		    	->execute();

	}
}
