Game:
  actAs: [ Timestampable, Signable ]
  tableName: game
  columns:
    game_id: { type: integer, primary: true, autoincrement: true }
    team1:   { type: string(100), notnull: true }
    team2:   { type: string(100), notnull: true }
    result:  { type: string(10) }
    active:  { type: boolean, default: true }

Odds:
  actAs: [ Timestampable, Signable ]
  tableName: odds
  columns:
     odds_id: { type: integer, primary: true, autoincrement: true }
     game_id: { type: integer, notnull: true }
     team1:   { type: string(10) }
     draw:    { type: string(10) }
     team2:   { type: string(10) }
     active:  { type: boolean, default: true }
  relations:
     Game: { local: game_id, foreign: game_id }

Bet:
  actAs: [ Timestampable, Signable ]
  tableName: bet
  columns:
     bet_id:  { type: integer, primary: true, autoincrement: true }
     user_id: { type: integer }
     game_id: { type: integer, notnull: true }
     pick:    { type: string(10) }
     odds:    { type: string(10) }
     amount:  { type: string(10) }
  relations:
     Game: { local: game_id, foreign: game_id }

UserInfo:
  tableName: user_info
  columns:
     user_id:  { type: integer, primary: true, autoincrement: true }
     balance:  { type: decimal }
     last_payday: { type: datetime }